### ISSUE TITLE
Erroneous information...

### ISSUE THREAD

**Issue by pezzell11** [mrandrewmills/Fixed-Width-Text-File-Toolkit#14]
There is erroneous information regarding my criminal background on your site. Could you please remove this?

**Comment by mrandrewmills** [comment]
Good morning, pezzell11

Thanks for reaching out to me directly instead of trying to get me in
trouble with the support folks at GitHub.

I assume you are referring to one of the sample data files in my fixed
width text file toolkit? If so, please let me know which file name and line
numbers contain the erroneous information. I'm willing to redact them.

Take care,

Andrew

**Comment by pezzell11** [comment]
mrandrewmills/Fixed-Width-Text-File-Toolkit - GitHub
https://github.com/mrandrewmills/Fixed-Width.../arrest-9-15-2014.txt
Sep 18, 2014 - ... 1ST OFF 2257 DOUBLE EAGLE CT RESTON, RESTON, VA 20191 ..... EZZELL PATRICIA LYNN 57 09/03/2014 5-1-4 DISORDERLY ...

Hello - thank you for your help.  The lines were somewhere between 233 and 257 .  I'm not exactly sure.  I am using a mobile device and I am not sure how to use it.  Anyway, I appreciate your assistance.

Thank you,
Patricia Ezzell

**Comment by mrandrewmills** [comment]
I've located the lines you've described and redacted them from the data file.  I also took the liberty of removing the example you gave from the previous comment, just as an added precaution.  And you're most welcome.

Andrew

**Comment by pezzell11** [comment]
Andrew - can you please tell me how long it will take for my information to be removed from the Internet, I'm sorry to keep bothering you but I don't know very much about this stuff.  Thanks again, Patricia

**Comment by mrandrewmills** [comment]
Good morning, Patricia

I think you are asking me how long it will be until Google searches for
your name stop turning up this information. Correct?

**Comment by pezzell11** [comment]
Yes Sir, that is correct

**Comment by mrandrewmills** [comment]
Just to be clear, I can only control what Google caches from *my* sites.  So if your information is also posted over at Fairfax Underground, for example, there is nothing I can do about that.

**Comment by pezzell11** [comment]
Okay, thanks anyway
